version: '3'
services:
  nanolitepikolite:
    build: ./php
    image: laravel:latest
    container_name: nanolitepikolite
    hostname: "nanolitepikolite"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_nanolitepikolite

  db_nanolitepikolite:
    image: mariadb:10.2
    container_name: db_nanolitepikolite
    restart: unless-stopped
    tty: true
    ports:
      - "63306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: nanolite
      MYSQL_PASSWORD: nanolitepikolite12
      MYSQL_ROOT_PASSWORD: nanolitepikolite123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_nanolitepikolite:
    build: ./nginx
    image: nginx_nanolitepikolite:latest
    container_name: nginx_nanolitepikolite
    hostname: "nginx_nanolitepikolite"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nanolitepikolite